### ISSUE TITLE
dyld: Symbol not found: _CLYAutoViewTracking error

### ISSUE THREAD

**Issue by omaralbeik** [Countly/countly-sdk-ios#118]
Hey :wave: 

I’m trying to activate rich push notifications on our new iOS app
I followed the instructions on https://resources.count.ly/docs/countly-sdk-for-ios-and-os-x#section-push-notifications

- Integrated Countly using Cocoapods, it was all working until I created the notifications extension and integrated Countly to the new target.
The app is crashing as soon as I run and I shows the following error:

```
dyld: Symbol not found: _CLYAutoViewTracking
  Referenced from: /var/containers/Bundle/Application/0AA19706-EE52-48A1-AEE9-CF3118910BF6/APPNAME.app/APPNAME
  Expected in: /private/var/containers/Bundle/Application/0AA19706-EE52-48A1-AEE9-CF3118910BF6/APPNAME.app/Frameworks/Countly.framework/Countly
 in /var/containers/Bundle/Application/0AA19706-EE52-48A1-AEE9-CF3118910BF6/APPNAME.app/APPNAME
```

Here is my Podfile:

```ruby
platform :ios, '10.0'

target 'APPNAME' do
  use_frameworks!
  pod 'Countly'
end

target 'APPNAME Notifications' do
  use_frameworks!
  pod 'Countly/NotificationService'
end
```

## Environment:
- Swift 4
- Xcode 9.2 (9C40b)
- macOS 10.13.3 (17D47)

I googled the problem and couldn't find a solution for hours now, your help is highly appreciated.

**Comment by erkanyildiz** [comment]
Tested with the exactly same environment. It works without any problems:

Environment:
macOS 10.13.3 (17D47)
Xcode 9.2 (9C40b)
Swift 4.0
CocoaPods 1.4.0

Podfile:
```
target 'CocoaPodsExtensionTestOnSwift' do
  use_frameworks!
  platform :ios,'10.0'
  pod 'Countly'
end

target 'CountlyNSE' do
  use_frameworks!
  platform :ios,'10.0'
  pod 'Countly/NotificationService'
end
 ```

`CLYAutoViewTracking` symbol should never be referenced on extension target at all.
Can you make sure your Podfile configuration is correct, and you are running the latest CocoaPods version (1.4.0).

Closing the issue here. 
We can continue in support channel.
Thanks.
