### ISSUE TITLE
Push notifications shown twice

### ISSUE THREAD

**Issue by marianpolek** [Countly/countly-sdk-ios#122]
### Expected Behavior

push will not show

### Current Behavior

push is shown. 

### Screenshots (if appropriate):
![screen shot 2018-04-09 at 09 18 24](https://user-images.githubusercontent.com/4357071/38484477-093c15bc-3bd7-11e8-9512-6e2a0a958736.png)

### Context

Hi, 

i have received twice push notifications, basically one from yours SDK and one is custom created by my code. 
Basically, my solution is visible on screenshot. I have to always comment out the code which is basically comented out on screenshot. 

### Your Environment

* Countly iOS SDK version - newest, 18.01
* Your iOS version - many 10.x and 11.x versions
* Any changes you have made to this SDK - one change, visible on screenshot (but it's basically fix)

**Comment by erkanyildiz** [comment]
Hi,
You are sending a notification from Countly Server, but notification is displayed twice?

SDK acts as `UNNotificationCenterDelegate` and when a notification is receviced in foreground:
- Checks if notification has Countly payload; if it has, shows it using the default system notification UI
- Checks if Application Delegate also acts as `UNNotificationCenterDelegate`; if so, forwards the method call and lets the notification also be handled there

I believe your implementation in your Application Delegate always shows the notification.
You should check if the notification comes from Countly Server, and not show the notification again.
Because if it comes from Countly Server, it is already shown by the SDK.

https://resources.count.ly/docs/countly-sdk-for-ios-and-os-x#section-handling-notifications-manually

If your problem is something else, can you explain it in more detail?

**Comment by marianpolek** [comment]
exactly as you said. 

but, problem is that i want to show only my custom banner (notification), not yours from countly. 
Or is it possible to have some custom design for your push notification ? and custom tap handling ? 

Thank you

**Comment by erkanyildiz** [comment]
Hi again, 
This change will cover your use case as well:
https://github.com/erkanyildiz/countly-sdk-ios/commit/a3c6af12191a023f9755c992f3c650dbb94af9d3
