### ISSUE TITLE
Jailbreak detection and App Review?

### ISSUE THREAD

**Issue by DrewHood** [Countly/countly-sdk-ios#125]
Sorry if this question seems superfluous but I just want to be sure. I'm trying out Countly for the first time and liking it a lot so far. Looking through the project I see CountlyDeviceInfo contains a jailbreak detection method inside `+ (BOOL)isJailbroken;`. [I've read that this is not allowed on the app store](https://forums.developer.apple.com/thread/43073). From what I can find, Apple used to provide an API for this several years ago, but then removed it. For now, I've commented the method out, as the information doesn't help me anyways. 

I'm pretty sure using `fopen("/bin/bash", "r");` could leave an app subject to rejection, even if they don't reject you every time. Do you know of anyone using Countly that has gotten feedback from App Review about this? Thanks. 

Edit: [An example of this type of code being rejected.](https://9to5mac.com/2016/05/10/security-research-stefan-esser-releases-iphone-ipad-jailbreak-detection-tool-in-ios-app-store/)

**Comment by DrewHood** [comment]
Sure, in Apple’s [App Review Guidelines, it states in section 2.5.2](https://developer.apple.com/app-store/review/guidelines/#software-requirements): 

> 2.5.2 Apps should be self-contained in their bundles, and may not read or write data outside the designated container area...

`/bin/bash` Is outside the app’s container.

**Comment by gorkem-cetin** [comment]
OK, good point. FYI; we didn't have any rejections because of Countly SDK but this may be worth having a look. Leaving it to @erkanyildiz ...

**Comment by DrewHood** [comment]
Glad to know there haven't been any rejections. Thanks for checking up on it.

**Comment by erkanyildiz** [comment]
Thank you for your concern. While we are aware that some jailbreak detection attempts (like checking for SC_info) are subject to reject, we have never got rejected so far due to `fopen("/bin/bash", "r");`. 

If this changes, we will update the method. For now, it is fine.

By the way, that app you mentioned did not get rejected due to mere jailbreak detection. It claims to be an `System and Security Info` app, and its content was against `2.19 Apps that provide incorrect diagnostic or other inaccurate device data will be rejected`.

Thanks again.
