### ISSUE TITLE
Create a separate target for iOS, macOS, tvOS frameworks (don't treat macOS as a 3rd class citizen)

### ISSUE THREAD

**Issue by spicymatt** [Countly/countly-sdk-ios#160]
I was expecting to use Countly in a MacOS app, but realized the module is not MacOS compatible for versions < 10.15 because the base SDK is set to iOS.

Wouldn't it be better to create different targets for different platforms, like most framework developers do. You keep the same code in each target, but each target can set its specifics.
In particular, you can set the deployment target for MacOS to be 10.13 or 10.14..whatever is more appropriate since your code compiles fine on 10.14 (for example).

Your web site advertises macOS as a 1st class citizen, but it is not, when peeking at your SDK. Minimal work is required to make it more universal.

### Expected Behavior

As a macOS framework consumer, I would expect a proper macOS framework with a target deployment of 10.14 at the least

### Current Behavior
The current SDK has only 1 framework that is targeted to iOS causing issues when integrated in a macOS app targeting os < 10.15

### Possible Solution
See above

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### More Description
I had to modify the SDK to integrate countly on a macOS 10.14 app.

### Your Environment

* Countly iOS SDK version : latest
* Your iOS version: not iOS, macOS 10.14
* Any changes you have made to this SDK: I changed the base SDK to macOS to make it work.
But I believe that the clean solution is to do as suggested above.

**Comment by erkanyildiz** [comment]
> don't treat macOS as a 3rd class citizen

We do not. 

> Your web site advertises macOS as a 1st class citizen, but it is not, when peeking at your SDK. Minimal work is required to make it more universal.

Please stop making false assumptions :)


> I had to modify the SDK to integrate countly on a macOS 10.14 app.

No, you do not need to modify the SDK, as long as you integrate it directly using the source files in your project, which is the first recommended method on our documentation. 

Most probably you are using Carthage or that Xcode project file which is created solely for Carthage support, which means you just prefer one of the alternative ways to integrate the SDK.

If one of the `alternative` integration methods does not live up to your expectations, just asking for it is enough. So, I kindly remind you to stop making false assumptions one more time :)

By the way, it was already in TODO since Feb 1, 2020, but could not catch the latest (20.04) release, as it is just an optional alternative integration method.

On the next release, it will be ready.

**Comment by spicymatt** [comment]
Hello,
Thanks for answering so quickly...on a sunday.
I did not mean to be rude. Sorry if I offended you.

I am not using Carthage. I downloaded the SDK and integrated your project in my xCode project as a framework, not as source files. The xCode project really looked like a framework building project so I did not really think harder about an alternative integration.
But I did read your documentation after your reponse and I realize that your recommended way to integrate is different (code only, no framework). 
Nonetheless, packaging a framework for the various platforms is a more convenient way to integrate things and I am looking forward to the change if you do it.
Once again, sorry for my comment and keep up your amazing work.
