### ISSUE TITLE
iOS Deployment Target

### ISSUE THREAD

**Issue by JonasDeichelmann** [Countly/countly-sdk-ios#175]
### Expected Behavior

Hi,
I really like your work and I'm enjoying working with it.
In Xcode I get the following warning:

"Showing Recent Messages
The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99."

### Possible Solution

Is it possible to set the Deployment-Target to iOS 9.0, so that the warning will disappear?

### Your Environment

* Countly iOS SDK version 20.11.1
* Your iOS version iOS 14.3
* Xcode-Version: Xcode-12.3
* Any changes you have made to this SDK / none

**Comment by multinerd** [comment]
Workaround: Drop this at the bottom of your podfile
This will automatically set the target to whatever you want after a `pod install`.

```ruby
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '5.3' # You don't need this line, but i left it in just in case.
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        end
    end
end
```

**Comment by JonasDeichelmann** [comment]
Hi @multinerd,
thank you for your advice. I really appreciate it.
I'm not using CocoaPods, instead I'm using SPM for integrating the package.

**Comment by erkanyildiz** [comment]
Hello,

I guess you are getting that warning due to Xcode 12 dropping support for iOS 8: https://developer.apple.com/documentation/xcode-release-notes/xcode-12-release-notes

And it is caused by
```
    platforms: 
    [
        .iOS(.v8),
        .macOS(.v10_10),
        .tvOS(.v9),
        .watchOS(.v2)
    ],
```
part in `Package.swift`, which reflects our current minimum supported deployment target iOS 8. 

Until we drop support for iOS 8 and iOS 9 and set our minimum supported deployment target as iOS 10, there is nothing we can do, I think.

This is still being discussed internally. When there is an update, I will be sharing it here again.

Thank you.
