### ISSUE TITLE
Session is not increased when calling endSession() and then beginSession() 

### ISSUE THREAD

**Issue by theanhaxon** [Countly/countly-sdk-ios#213]
### Expected Behavior

I followed the documents https://support.count.ly/hc/en-us/articles/360037753511-iOS-watchOS-tvOS-macOS#manual-sessions to manual end/begin session. 
I start session every time user goes to forceground and end session every time users goes to background.
- Start at: func applicationDidBecomeActive(_ application: UIApplication) { }
- End at: func applicationWillResignActive(_ application: UIApplication) {  }
I also set "enableDebug = true", the Countly info log shows as expected
![Screen Shot 2022-11-23 at 11 25 17](https://user-images.githubusercontent.com/100405076/203469122-f1ba697a-ea53-48ac-b643-13463a781323.png)

### Current Behavior

But the session is not increased on Countlly dashboard when I call beginSession() then call endSession()
![Screen Shot 2022-11-23 at 11 27 11](https://user-images.githubusercontent.com/100405076/203469386-442ab0d4-dcc1-4183-ba41-7e5b5596b8dd.png)

### Steps to Reproduce (for bugs)

1. Setup manual session "config.manualSessionHandling = true"
2. call method beginSession() at "applicationDidBecomeActive(_ application: UIApplication) { }"
3. call method endSession() at "applicationWillResignActive(_ application: UIApplication) {  }"
4. Repeat step 2 and 3 few times.
5. Go to Countly dashboard and check the number of session for the user.

### Your Environment

* Countly iOS SDK version: 22.6.2
* Your iOS version: 16.0
* Any changes you have made to this SDK

**Comment by ijunaid** [comment]
@theanhaxon this is the expected behaviour of Countly SDK, In case a user becomes active just at the end of the inactivity timer or just at the end of the session, Countly servers provide a grace period to extend the session instead of terminating it. This “session cooldown” value is 15 seconds by default and can be changed from the Countly dashboard under the settings section.
Please check this link for more details about sessions:
https://support.count.ly/hc/en-us/articles/9290669873305#sessions

**Comment by theanhaxon** [comment]
@ijunaid Thank for your information. This issue can be closed
