### ISSUE TITLE
Events appear very delayed in Countly dashboard 

### ISSUE THREAD

**Issue by PatrickGaissert** [Countly/countly-sdk-ios#265]
Hi, we seem to experience a long delay between events happening in the app and them actually appearing in the Countly GUI. The delay is between 10 and 30 minutes which makes feature testing extremely difficult. The issue started about 4-6 weeks ago, reverting to a previous SDK version doesn't seem to change the behavior. Putting the app in the background and foreground again also doesn't mitigate the issue. We don't have this issue with the Android SDK.

Is anyone else experiencing this or has any input on how to solve it?

### Your Environment
* Countly iOS SDK version 23.8.3
* iOS 17.0

**Comment by ijunaid** [comment]
Hello @PatrickGaissert,
Thank you for your report. Could you kindly share the SDK version to which you reverted in order to resolve this issue? We are currently investigating the matter.

**Comment by PatrickGaissert** [comment]
I'm pretty sure we reverted to 23.2.3 but since we didn't see any change in behavior we figured it might be a server or GUI issue on the side of the dashboard instead of a client SDK issue. Obviously we're not sure. Thank you for investigating!

**Comment by ijunaid** [comment]
Hello @PatrickGaissert,
I sincerely apologize for the delay in responding to your message. Thank you for providing this information.
I appreciate your insights into potential causes of the issue. It’s a good idea to check the incoming data logs on the dashboard. Sometimes, data might be delayed in appearing on the GUI due to various calculations and internal implementations on the server side. By examining the incoming data logs, you can monitor the data in real-time as requests are sent from the client side.

For more detailed information on when data will show up on the dashboard, you can refer to this link:
https://support.count.ly/hc/en-us/articles/900000908046-Getting-started-with-SDKs#h_01HABSX9KX8X421H9SSG0YDX7G

For more details about incoming data logs, you can refer to this link:
https://support.count.ly/hc/en-us/articles/4404570865433-Utilities#h_01HBC3FWCAWAN8YQ4YEH6VG8B5
