### ISSUE TITLE
Crash reporting broken

### ISSUE THREAD

**Issue by yuriy128** [Countly/countly-sdk-ios#79]
1. CrashReporting.mm CountlyExceptionHandler code is using HTTPMethod POST and passing everything including app_key, device_id, and crash inside of HTTPBody. When testing this with try.count.ly, server response with an error message: "Missing app_key or device_id". I have tested and the only thing that works with try.count.ly is if you use GET and put everything in the query string.
2. Error handling is wrong: after sending sendSynchronousRequest, code checks **error** and **recvData** variables, but does not check the dictionary that server returns. So in this case when server is not returning Success, the crash report is actually being lost.
3. Even if #2 did have the correct check for the server reply, current implementation calls sendCrashReportLater, which in-turn will call saveToFile. However, this **saveToFile** function actually does a **dispatch_async**, and, since the application is being terminated, will actually never be called. Hence another bug, when crash report will be lost.
4. saveToFile is problematic since it uses a dispatch_async. For example, if application is about to terminate, this will be called to save the events to a file. However, since it's using dispatch_async, it is not guaranteed that the code will actually complete, hence there is a potential for event loss. This is actually quite easy to reproduce, put in a [NSThread sleepForTimeInterval:5.0] inside of saveToFile dispatch_async, accumulate some events, and kill the application, those events will be lost.

**Comment by erkanyildiz** [comment]
Hi yuri,

Thanks for contacting.

1) It looks like it is a problem with try server. My test server (16.02.01) works fine with POST. No need to modify something. If you send me an email I can share server details, so you can test :)

2) For now, Crash Reporting and Push Notifications does not comply with our latest SDK Development Guide, refactoring and updating is still in progress. You can see these are the only parts still using NSURLConnection instead of NSURLSession. That is why server response is not checked for that success dictionary. Currently, if there is an error or if there is no response, it is considered crash report could not be delivered. 

3 & 4) After the SDK update, saveToFile will be called synchronously for both CrashReporting and applicationWillTerminate callback, so there will be no problem.

By the way, I am on vacation now. I will continue working on them early May. 
So, I can say roughly estimated time for these updates are mid May.

Thanks again.

**Comment by ar2rsawseen** [comment]
Hello,
I will recheck try server and get back to you.

**Comment by yuriy128** [comment]
Btw, i was testing against Countly's enterprise cloud server, this should
always work.

**Comment by ar2rsawseen** [comment]
Hello,
just retested try.count.ly, cloud.count.ly and test server and all work correctly with post.
Can you provide any specific steps to reproduce this?

**Comment by yuriy128** [comment]
Hmm, didn't do anything special, but i was basically getting "missing
app_key or missing device_id" error. Maybe there are some nodes on
try.count.ly that are running old server code? I will try again in the
morning.

**Comment by ar2rsawseen** [comment]
Could it be some ios version specific, that server does not understand post data?

**Comment by yuriy128** [comment]
Was getting a very specific message, testing with your own "testCrash"
method.

**Comment by yuriy128** [comment]
Do you guys have access to the logs from the enterprise try server, you should be able to see requests coming in yesterday that had this issue. I tried today with DHC plugin and the POST request works now. Which makes me believe that you might have an out of date server somewhere that is causing this issue. The other issues: #2,#3,& #4 still apply.

**Comment by erkanyildiz** [comment]
Hi again, 

This commit solves #3 and #4
https://github.com/erkanyildiz/countly-sdk-ios/commit/34eb96e1bb492fa58c6b6933bba90e7827fa5cc4

#2 will be solved when refactor finished. 
Thanks.

**Comment by erkanyildiz** [comment]
And this fixes #2:
e20c3442d72ca5f591a88a2fe15b8a66e8d1fc43

Soon I will merge to main.

Thanks again.
