### ISSUE TITLE
app_key is saved as part of persistance file

### ISSUE THREAD

**Issue by yuriy128** [Countly/countly-sdk-ios#80]
This is a potential bug, here's the scenario where this is really bad:

Let's say you have a client application that is using specific app_key, they already have an established user base as well. These users might have some countly requests stored that have not been synced yet. Now, application developer changes their app_key and removes old app_key. Users get the updated application with the new app key, however queued up requests with the old app_key are now failing and will never get cleared up in this case. Also, new events will never get delivered either since they are in the back of the queue.... Clients will stop sending events at this point and the event file keeps growing.

**Comment by yuriy128** [comment]
To resolve this, do not add [self queryEssentials] to the queue, but add it right before sending the request over.

**Comment by ar2rsawseen** [comment]
I would not say that scenario is not so bad.

Because when you update an app and change app_key to new one, you **expect new data** after update to be sent to new app, and that is exactly what is happening. Because queued requests with old app key would be old requests before update, and only new ones will be with new app_key.

And properly configured production Countly server will still respond with success even if the app does not exist, so these requests won't pile up (aka Safer API responses disabled)

But another point is that we need to store queryEssentials with queued requests for many other reasons. Like when switching deviceId when multiple different users use the app, etc, we need to ensure that queries are executed with the data the events occurred. And not tampered afterwards.

Our whole structure depends on that :)

**Comment by yuriy128** [comment]
Fair point about device id. Then, perhaps take out app_key from query
essentials and treat it just like host?
